//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public int id_Est { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public int Matricula { get; set; }
        public Nullable<int> CodCar { get; set; }
        public string Sexo { get; set; }
    }
}
